name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file src/main.bicep

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Validate Bicep template
        run: |
          az deployment group validate \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file ./src/main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    strategy:
      matrix:
        storageAccountName: [stgacc0986890, storageacc2890654]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./src/main.bicep
          parameters: storageAccountName=${{ matrix.storageAccountName }}
          deploymentName: ${{ github.run_id }}-${{ matrix.storageAccountName }}
